%==============================MASTER======================================
Control_MASTER = {
    "C_24_CartDel", "C_24_CRoute_Out", "C_24_Request", "C_24_CRoute_In", ...
    "C_25_CartDel", "C_25_CRoute_Out", "C_25_Request", "C_25_CRoute_In", ...
    "C_26_CartDel", "C_26_CRoute_Out", "C_26_Request", "C_26_CRoute_In", ...
    "C_27_CartDel", "C_27_CRoute_Out", "C_27_Request", "C_27_CRoute_In", ...
    "C_28_CartDel", "C_28_CRoute_Out", "C_28_Request", "C_28_CRoute_In", ...
    "C_29_CartDel", "C_29_CRoute_Out", "C_29_Request", "C_29_CRoute_In"
};
Actuators_MASTER = {
    "F_22_Led_On", "F_22_Led_Off", "F_22_Conveyor", ...
    "F_24_Release_FB", "F_25_Release_FB", "F_26_Release_FB", "F_27_Release_FB", "F_28_Release_FB", "F_29_Release_FB"
};
Sensors_MASTER = {
    "O_20_On", "O_20_Off", "O_20_Controler_On", ...
    "O_24_Cart_Stat", "O_24_Cart_Next", "O_24_Optic", "O_24_Count", "O_24_Pist_Bck", ...
    "O_25_Cart_Stat", "O_25_Cart_Next", "O_25_Optic", "O_25_Count", "O_25_Pist_Bck", ...
    "O_26_Cart_Stat", "O_26_Cart_Next", "O_26_Optic", "O_26_Count", "O_26_Pist_Bck", ...
    "O_27_Cart_Stat", "O_27_Cart_Next", "O_27_Optic", "O_27_Count", "O_27_Pist_Bck", ...
    "O_28_Cart_Stat", "O_28_Cart_Next", "O_28_Optic", "O_28_Count", "O_28_Pist_Bck", ...
    "O_29_Cart_Stat", "O_29_Cart_Next", "O_29_Optic", "O_29_Count", "O_29_Pist_Bck"
};
Var_MASTER = {Control_MASTER,Actuators_MASTER,Sensors_MASTER};
%==============================TESTING=====================================
ASI_TESTING = {
    "A_74_Request", "A_74_No_Cart", "A_74_Cart_Full", "A_74_CRoute_Out", "A_74_CRoute_In80", ...
    "A_73_TestCartID", "A_74_Cart_Stat", "A_74_Cart_Next", "A_74_Optic", "A_74_Count", ...
    "A_74_Pist_Bck", "A_74_Release_FB", "A_74_CRoute_In"
};
Control_TESTING = {
    "C_75_Initialization", "C_75_ID_Delivery1", "C_75_ID_Delivery2", "C_75_Part_Del", "C_75_RQ_Part_Del", ...
    "C_75_RQ_Wrong", "C_75_Identified80", "C_75_Requested80", "C_72_Profibus", "C_75_RQ_Delivery1", ...
    "C_75_RQ_Delivery2", "C_75_Identified", "C_75_Requested"
};
Actuators_TESTING = {
    "F_72_Elev_Down", "F_72_Elev_Up", "F_72_Eject_Part", "F_72_Air_On", ...
    "F_73_Led_Start", "F_73_Led_Reset", "F_73_Led_Extra1", "F_73_Led_Extra2", ...
    "F_73_Panel_O4", "F_73_Panel_O5", "F_73_Panel_O6", "F_73_Panel_O7"
};
Sensors_TESTING = {
    "O_70_SInductive", "O_70_SPart", "O_70_SStation", "O_70_SPart_Height", "O_70_Elev_High", ...
    "O_70_Elev_Low", "O_70_Pist_Back", "O_71_Start", "O_71_Stop", "O_71_Key_Pos", "O_71_Reset", ...
    "O_71_Panel_I4", "O_71_Panel_I5", "O_71_Panel_I6", "O_71_Panel_I7"
};
Var_TESTING = {ASI_TESTING,Control_TESTING,Actuators_TESTING,Sensors_TESTING};
%===============================HD1========================================
ASI_HD1 = {
    "A_54_Request", "A_54_No_Cart", "A_54_Cart_Full", "A_54_CRoute_Out", ...
    "A_53_SortCartID", "A_54_Cart_Stat", "A_54_Cart_Next", "A_54_Optic", "A_54_Count", ...
    "A_54_Pist_Bck", "A_54_Release_FB", "A_54_CRoute_In"
};
Control_HD1 = {
    "C_55_Initialization", "C_55_PD_Sort", "C_52_Profibus", "C_55_Start", "C_55_Cart2Del"
};
Actuators_HD1 = {
    "F_52_Claw_2_Del", "F_52_Claw_2_Cart", "F_52_Claw_Down", "F_52_Close_Claw", ...
    "F_53_Led_Start", "F_53_Led_Reset", "F_53_Led_Extra1", "F_53_Led_Extra2", ...
    "F_53_Panel_O4", "F_53_Panel_O5", "F_53_Panel_O6", "F_53_Panel_O7"
};
Sensors_HD1 = {
    "O_50_Part_Reserve", "O_50_Claw_Cart", "O_50_Claw_Del", "O_50_Claw_Reserve", ...
    "O_50_Claw_Low", "O_50_Claw_High", "O_50_Part_in_Claw", "O_51_Start", "O_51_Stop", ...
    "O_51_Key_Pos", "O_51_Reset", "O_51_Panel_I4", "O_51_Panel_I5", "O_51_Panel_I6", "O_51_Panel_I7"
};
Var_HD1 = {ASI_HD1,Control_HD1,Actuators_HD1,Sensors_HD1};
%===============================HD2========================================
ASI_HD2 = {
    "A_94_Request", "A_94_No_Cart", "A_94_Cart_Full", "A_94_CRoute_Out", ...
    "A_93_ProcCartID", "A_94_Cart_Stat", "A_94_Cart_Next", "A_94_Optic", "A_94_Count", ...
    "A_94_Pist_Bck", "A_94_Release_FB", "A_94_CRoute_In"
};
Control_HD2 = {
    "C_95_Initialization", "C_95_PD_Proc", "C_95_PD_Cart", "C_92_Profibus", ...
    "C_95_Start", "C_95_Cart2Del", "C_95_Del2Cart"
};
Actuators_HD2 = {
    "F_92_Claw_2_Cart", "F_92_Claw_2_Del", "F_92_Claw_Down", "F_92_Close_Claw", ...
    "F_93_Led_Start", "F_93_Led_Reset", "F_93_Led_Extra1", "F_93_Led_Extra2", ...
    "F_93_Panel_O4", "F_93_Panel_O5", "F_93_Panel_O6", "F_93_Panel_O7"
};
Sensors_HD2 = {
    "O_90_Part_Reserve", "O_90_Claw_Del", "O_90_Claw_Cart", "O_90_Claw_Reserve", ...
    "O_90_Claw_Low", "O_90_Claw_High", "O_90_Part_in_Claw", "O_91_Start", "O_91_Stop", ...
    "O_91_Key_Pos", "O_91_Reset", "O_91_Panel_I4", "O_91_Panel_I5", "O_91_Panel_I6", "O_91_Panel_I7"
};
Var_HD2 = {ASI_HD2,Control_HD2,Actuators_HD2,Sensors_HD2};
%===============================ROBOT======================================
ASI_ROBOT = {
    "A_34_Request", "A_34_No_Cart", "A_34_Cart_Full", "A_34_CRoute_Out", ...
    "A_32_RoboCartID", "A_34_Cart_Stat", "A_34_Cart_Next", "A_34_Optic", "A_34_Count", ...
    "A_34_Pist_Bck", "A_34_Release_FB", "A_34_CRoute_In"
};
Control_ROBOT = {
    "C_35_Part_Del", "C_30_Robot1", "C_30_Robot2"
};
Actuators_ROBOT = {
    "F_33_Led_Start", "F_33_Led_Reset", "F_33_Led_Extra1", "F_33_Led_Extra2", ...
    "F_33_Spring_Cyl", "F_33_Cover_Cyl"
};
Sensors_ROBOT = {
    "O_31_Start", "O_31_Stop", "O_31_Reset", "O_31_Part_in_Claw", "O_31_Orientation", ...
    "O_32_Sp_Cyl_Bck", "O_32_Sp_Cyl_Fwd", "O_32_Co_Cyl_Bck", "O_32_Co_Cyl_Fwd", ...
    "O_32_Sp_PickUp", "O_32_Co_PickUp", "O_32_CoMag_Empty"
};
%===========================STORAGE========================================
ASI_STORAGE = {
    "A_44_Request", "A_44_No_Cart", "A_44_Cart_Full", "A_44_CRoute_In", ...
    "A_43_StorCartID", "A_44_Cart_Stat", "A_44_Cart_Next", "A_44_Optic", "A_44_Count", ...
    "A_44_Pist_Bck", "A_44_Release_FB", "A_44_CRoute_Out"
};
Control_STORAGE = {
    "C_45_Initialization", "C_42_Profibus", "C_45_Start", "C_45_StorePart", "C_45_RetrievePart"
};
Actuators_STORAGE = {
    "F_43_Led_Start", "F_43_Led_Reset", "F_43_Led_Extra1", "F_43_Led_Extra2", ...
    "F_43_Panel_O4", "F_43_Panel_O5", "F_43_Panel_O6", "F_43_Panel_O7"
};
Sensors_STORAGE = {
    "O_41_Start", "O_41_Stop", "O_41_Key_Pos", "O_41_Reset", ...
    "O_41_Panel_I4", "O_41_Panel_I5", "O_41_Panel_I6", "O_41_Panel_I7"
};
Var_NODE = {ASI_STORAGE,Control_STORAGE,Actuators_STORAGE,Sensors_STORAGE,...
    ASI_ROBOT,Control_ROBOT,Actuators_ROBOT,Sensors_ROBOT};
%==========================SORT============================================
Control_SORT = {
    "C_65_Initialization", "C_65_ID_1", "C_65_ID_2", "C_62_Profibus","C_65_Part_Sorted", ...
    "C_65_RBS_Output", "C_65_RSB_Output", "C_65_BRS_Output", "C_65_BSR_Output", ...
    "C_65_SRB_Output", "C_65_SBR_Output"
};
Actuators_SORT = {
    "F_62_Conveyor", "F_62_P1", "F_62_P2", "F_62_Identify", ...
    "F_63_Led_Start", "F_63_Led_Reset", "F_63_Led_Extra1", "F_63_Led_Extra2", ...
    "F_63_Panel_O4", "F_63_Panel_O5", "F_63_Panel_O6", "F_63_Panel_O7"
};
Sensors_SORT = {
    "O_60_SPart", "O_60_SInd", "O_60_SPhoto", "O_60_Part_Pass", ...
    "O_60_SL1_Bck", "O_60_SL1_Fwd", "O_60_SL2_Bck", "O_60_SL2_Fwd", ...
    "O_61_Start", "O_61_Stop", "O_61_Key_Pos", "O_61_Reset", ...
    "O_61_Panel_I4", "O_61_Panel_I5", "O_61_Panel_I6", "O_61_Panel_I7"
};
Var_SORT = {Control_SORT,Actuators_SORT,Sensors_SORT};
%===============================PROC=======================================
Control_PROC = {
    "C_105_Initialization", "C_105_Part_ready", "C_105_Test_Ok", "C_105_Test_Fail", "C_102_Profibus", ...
    "C_103_RQ_Turns", "C_105_Start", "C_105_Test", "C_105_TestDrill", "C_105_Rotation"
};
Actuators_PROC = {
    "F_102_Drill_On", "F_102_RT_On", "F_102_Drill_Down", "F_102_Drill_Up", "F_102_Drill_Pin", "F_102_Test_Pin", ...
    "F_103_Led_Start", "F_103_Led_Reset", "F_103_Led_Extra1", "F_103_Led_Extra2", ...
    "F_103_Panel_O4", "F_103_Panel_O5", "F_103_Panel_O6", "F_103_Panel_O7"
};
Sensors_PROC = {
    "O_100_PInit_Pos", "O_100_PDrill_Pos", "O_100_PTest_Pos", "O_100_SDrill_High", "O_100_SDrill_Low", ...
    "O_100_RT_Sensor", "O_100_PTest_Ok", "O_101_Start", "O_101_Stop", "O_101_Key_Pos", "O_101_Reset", ...
    "O_101_Panel_I4", "O_101_Panel_I5", "O_101_Panel_I6", "O_101_Panel_I7"
};
Var_PROC = {Control_PROC,Actuators_PROC,Sensors_PROC};
%===============================DIST=======================================
Control_DIST = {
    "C_85_Initialization", "C_85_Part_Del", "C_85_Part_Mag", "C_86_Mag_Parts", "C_87_RQ_MParts", ...
    "C_82_Profibus", "C_83_RQ_Parts", "C_85_Start", "C_85_Single", "C_85_Continuous", "C_85_Counted"
};
Actuators_DIST = {
    "F_82_Pist_Adv", "F_82_Suction_On", "F_82_Suction_Off", "F_82_Arm_2_Del", "F_82_Arm_2_Mag", ...
    "F_83_Led_Start", "F_83_Led_Reset", "F_83_Led_Extra1", "F_83_Led_Extra2", ...
    "F_83_Panel_O4", "F_83_Panel_O5", "F_83_Panel_O6", "F_83_Panel_O7"
};
Sensors_DIST = {
    "O_80_Mag_Full", "O_80_Pist_Back", "O_80_Pist_Fwd", "O_80_Part_Stuck", "O_80_Arm_Mag", "O_80_Arm_Del", "O_80_Mag_Empty", ...
    "O_81_Start", "O_81_Stop", "O_81_Key_Pos", "O_81_Reset", ...
    "O_81_Panel_I4", "O_81_Panel_I5", "O_81_Panel_I6", "O_81_Panel_I7"
};
Var_DIST = {Control_DIST,Actuators_DIST,Sensors_DIST};

AllVariables = { ...
    Var_MASTER, ...
    Var_NODE, ...
    Var_HD1, ...
    Var_SORT, ...
    Var_TESTING, ...
    Var_DIST, ...
    Var_HD2, ...
    Var_PROC ...
};

save('Tags_OPCUA.mat', 'AllVariables')