@startuml
hide circle
skinparam linetype ortho

entity "Products" as products {
  *product_type : ProductType <<PK>>
  --
  *Station1Stop : BOOL
  Station1Op : VARCHAR(50)
  *Station2Stop : BOOL
  Station2Op : VARCHAR(50)
  *Station3Stop : BOOL
  Station3Op : VARCHAR(50)
  *Station4Stop : BOOL
  Station4Op : VARCHAR(50)
  *Station5Stop : BOOL
  Station5Op : VARCHAR(50)
  *Station6Stop : BOOL
  Station6Op : VARCHAR(50)
}

entity "Orders" as orders {
  *order_id : INT <<PK>>
  --
  *nb_product : INT
  *product_type : ProductType <<FK>>
  *status : ProductionStatus 
}

entity "Production" as production {
  *productSN : INT <<PK>>
  --
  *order_id : INT <<FK>>
  *cart_id : INT
  *current_station : Station
  *visited_stations : VARCHAR(255)
  *status : ProductionStatus 
}

entity "History" as history {
  *history_id : INT <<PK>>
  --
  *order_id : INT
  *productSN : INT
  *product_type : ProductType
  *completion_date : DATE
  *completion_time : TIME
}

enum "ProductType" {
  A
  B
  C
}

enum "Station" {
  Station1
  Station2
  Station3
  Station4
  Station5
  Station6
}

enum "ProductionStatus" {
  WAITING
  IN_PROGRESS
  PAUSED
  FINISHED
}

' Relations
products "1" -- "*" orders : "Is ordered"
orders "1" -- "1...*" production : "Generates"
production "1" -- "0..1" history : "Becomes"
orders "1" -- "*" history : "Archives"

@enduml